### ISSUE TITLE
karma in watch mode broken form tests when refresh

### ISSUE THREAD

**Issue by jadir-junior** [testing-library/angular-testing-library#309] opened 2022-07-25 16:44 UTC
I try test a form required, the first time test pass normal, but when I change the file and karma refresh the tests all tests in form broken

**app.component.ts**
```
import {
  FormBuilder,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <form [formGroup]="form">
      <input type="text" formControlName="name" aria-label="name" />
      <div *ngIf="name.invalid && name.touched">
        <p aria-label="error name" *ngIf="name.errors?.['required']">
          Campo obrigatorio
        </p>
      </div>
    </form>
  `,
})
export class AppComponent {
  form: FormGroup = this.fb.group({
    name: ['', [Validators.required]],
  });

  constructor(private fb: FormBuilder) {}

  get name(): FormControl {
    return this.form.get('name') as FormControl;
  }
}

```

**app.component.testing-library.spec.ts **
```
import { render, screen } from '@testing-library/angular';

import { AppComponent } from './app.component';
import { ReactiveFormsModule } from '@angular/forms';
import userEvent from '@testing-library/user-event';

describe('Testing library Form', () => {
  const { getByLabelText, getByText } = screen;
  const setup = () => {
    return render(AppComponent, {
      imports: [ReactiveFormsModule],
    });
  };

  it('should render a component with testing library', async () => {
    await setup();

    expect(getByLabelText('name')).toBeInTheDocument();
  });

  it('should show erro message required with testing library', async () => {
    const { fixture } = await setup();
    fixture.detectChanges();

    const input = getByLabelText('name');

    await userEvent.click(input);
    await userEvent.tab();

    console.log('COMMENT TO REFRESH');

    expect(getByText('Campo obrigatorio')).toBeInTheDocument();
  });
});
```

At first time the testing pass:

![Screenshot from 2022-07-25 13-35-38](https://user-images.githubusercontent.com/8190617/180829632-20b86874-611f-4614-a8b9-17a73cebc9be.png)

But when I change some file, this happen:

![Screenshot from 2022-07-25 13-36-58](https://user-images.githubusercontent.com/8190617/180829804-888a9533-20fb-4094-abd5-c820e7b22cda.png)

When I refresh with F5, the tests back to pass:

![Screenshot from 2022-07-25 13-38-01](https://user-images.githubusercontent.com/8190617/180830050-e28f43a4-96f1-4ba1-beb6-f365b573adac.png)
![Screenshot from 2022-07-25 13-38-11](https://user-images.githubusercontent.com/8190617/180830035-fe2635ab-59aa-435f-937f-205c16ef7db8.png)

I thought that was karma or karma-launch, but if I test with normal library angular this work normally
**app.component.ts**
```
import { ComponentFixture, TestBed } from '@angular/core/testing';

import { AppComponent } from './app.component';
import { By } from '@angular/platform-browser';
import { DebugElement } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';

const dispatchFakeEvent = (
  element: EventTarget,
  type: string,
  bubbles: boolean = false
): void => {
  const event = document.createEvent('event');
  event.initEvent(type, bubbles, false);
  element.dispatchEvent(event);
};

const markFieldAsTouched = (element: DebugElement) => {
  dispatchFakeEvent(element.nativeElement, 'blur');
};

describe('AppComponent', () => {
  let fixture: ComponentFixture<AppComponent>;
  let component: AppComponent;

  const setup = async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent],
      imports: [ReactiveFormsModule],
    }).compileComponents();

    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  };

  it('should render a component with testing angular', async () => {
    await setup();

    expect(component).toBeTruthy();
  });

  it('should show erro message required with testing angular', async () => {
    await setup();

    const appComponent: DebugElement = fixture.debugElement;

    const input = appComponent.query(By.css('input'));
    markFieldAsTouched(input);

    fixture.detectChanges();

    const error = appComponent.query(By.css('p')).nativeElement;

    expect(error).toBeTruthy();
    expect(error).toHaveTextContent('Campo obrigatorio');
  });
});

```

the env in my github:
https://github.com/jadir-junior/angular-karma-and-testing-library

**Comment by timdeschryver** [comment] 2022-07-26 05:01
Hi, thanks for the reproduction.
I tried to reproduce it, but I wasn't really successful.
Is this something that always fails for you, because I tried changing the component and the test multiple times but the test keeps passing.

I suspect that it's a timing issue.
Could you try the following assertion?

```ts
// use findBy instead of getBy
expect(await screen.findByText('Campo obrigatorio')).toBeInTheDocument();
```

**Comment by jadir-junior** [comment] 2022-07-26 12:44
I try to simulate 
![bug](https://user-images.githubusercontent.com/8190617/181008495-faee2b14-802f-43a5-9d00-0748eaf86222.gif)

**Comment by timdeschryver** [comment] 2022-07-26 16:17
@jadir-junior thanks again.
It seems like it doesn't blur correctly, you could use `fireEvent.blur` for now which should work:


```ts
  it('should show error message required with testing library', async () => {
    await setup();

    const input = getByLabelText('name');
    fireEvent.blur(input);
    expect(screen.getByText('Campo obrigatorio')).toBeInTheDocument();
  });
```

**Comment by rothsandro** [comment] 2022-07-28 11:43
The browser needs to be focused, see https://github.com/testing-library/user-event/issues/553

**Comment by timdeschryver** [comment] 2022-12-14 12:43
Needs to be fixed in userEvent

**Closed by timdeschryver** 2022-12-14 12:43 UTC
