### ISSUE TITLE
This library calls detect changes on every property change

### ISSUE THREAD

**Issue by antischematic** [testing-library/angular-testing-library#322] opened 2022-11-20 11:50 UTC
```ts
@Component({
  template: `
    count: {{ count }}
    <button (click)="increment()">Increment</button>
  `
})
export class Counter {
  elementRef = inject(ElementRef)
  count = 0

  increment() {
    this.count++
    this.count++
    this.count++

    expect(elementRef.nativeElement).toHaveTextContent("count: 0")
  }
}
```

```ts
await render(Counter)

fireEvent.click(screen.getByText("Increment"))
```

Expected result: `count: 0`
Actual result: `count: 3`

This is not correct Angular behavior and breaks custom change detection strategies.

Proposal: Use `ComponentRef#setInput` to change component properties instead.

**Comment by timdeschryver** [comment] 2022-11-21 18:55
While I agree that this isn't the Angular behavior, I do expect the test case to behave like this.
Could you share some insights about "breaks custom change detection strategies" for your use case please?

**Comment by antischematic** [comment] 2022-11-21 20:58
In my use case I am using proxies to generate a dependency graph and checking if those dependencies are dirty with change detection hooks. Using this with `render` causes two problems:

1. I'm unable to write tests that assert change detection runs X number of times, because this lib is calling `detectChanges` when I'm not expecting it.
2. In some cases this causes infinite recursion in tests that mutate dependencies inside reactive functions.
3. ngOnChanges is called when I'm not expecting it.

https://github.com/antischematic/angular-state-library/blob/35f81fed397af75b87e68681e0be56e026769d79/projects/core/src/tests/invoke.spec.ts

Replace `import { render } from "./utils/render"` workaround with `import {render} from "@testing-library/angular"` and run `ng test core` to reproduce the failing test cases.

**Comment by timdeschryver** [comment] 2022-11-22 17:08
I see, thanks for clarifying this @antischematic.
What do you think of adding a config property (that could be set globally), to disable the automatic change detection?
I think for most of the projects, the default should still invoke the change detection.

**Comment by antischematic** [comment] 2022-11-22 20:29
I think automatic change detection should be kept while changing the implementation so it aligns better with real app behaviour.

1. Automatic change detection should be done using `fixture.autoDetectChanges`. This makes it run like a normal app.
2. Passing `detectChanges: false` should disable automatic change detection.
3. Calling `change` should only set input properties using `fixture.setInput`. This method throws an error when trying to set a non-input property.

(See example here)[https://github.com/antischematic/angular-state-library/blob/master/projects/core/src/tests/utils/render.ts].

These changes would require a bump to min Angular version >= 14.1. It should also be possible to get this working with a wrapper component using `reflectComponentType` but haven't tried it yet.

**Comment by timdeschryver** [comment] 2022-11-23 17:52
Thanks again for the input @antischematic .
After toying with it for a while, I do have see some concerns.

`setInput` fails when the property isn't marked with `@Input()`, so this would fail for output properties. Sadly, this doesn't throw but it creates a `console.error`, which makes it harder to fall back to the current behavior. 

I've tried `autoDetectChanges` in the past, but this didn't work the way I wanted it to do. This could have changed now, and is something that I need to investigate soon.

`reflectComponentType` is interesting, and we could make use of it in some places. Sadly, we also allow the `render('<app-component></app-component>')` syntax, which is useful for some scenarios but this also means that `reflectComponentType` does not help a lot here because we don't know the type of the component, and we also create a wrapper component to render it.

I do want to allow a more fine-grained control over the inputs/outputs properties, and the CD.
I'm thinking of adding an `componentInputs` and `componentOutputs` render options, which would allow us to implement your suggestions. We could also gradually phase out `componentProperties` to give a better experience later.

**Comment by timdeschryver** [comment] 2022-11-25 12:36
@antischematic feel free to try out the beta version (13.0.0-beta.6).
You can find the changes on the [release page](https://github.com/testing-library/angular-testing-library/releases).

**Comment by timdeschryver** [comment] 2022-12-08 18:36
@antischematic sorry to re-ping you but did you had the chance to test the beta release?

**Comment by timdeschryver** [comment] 2022-12-10 18:10
@antischematic good catch about the ngOnChanges firing twice.
I'm not able to reproduce that ngOnChanged fires when there's no inputs though, for example:

- during changeInputs https://github.com/testing-library/angular-testing-library/blob/beta/projects/testing-library/tests/changeInputs.spec.ts#L53
- during change https://github.com/testing-library/angular-testing-library/blob/beta/projects/testing-library/tests/change.spec.ts#L68
- during render https://github.com/testing-library/angular-testing-library/blob/beta/projects/testing-library/tests/render.spec.ts#L255

This version is available as `13.0.0-beta.9` and will probably be released next week

**Comment by antischematic** [comment] 2022-12-10 19:47
@timdeschryver Thanks for that, my tests are now passing 13.0.0-beta-9 without any issues.

**Comment by timdeschryver** [comment] 2022-12-14 12:40
This is released in v13 🥳
Thanks @antischematic !

**Closed by timdeschryver** 2022-12-14 12:40 UTC

**Comment by timdeschryver** [comment] 2022-12-14 12:42
@all-contributors please add @antischematic for bug, ideas
