### ISSUE TITLE
Module '"@angular/core/testing"' has no exported member 'DeferBlockState'.

### ISSUE THREAD

**Issue by matteoveraldi** [testing-library/angular-testing-library#421] opened 2023-11-17 15:52 UTC
Hi,
I am unable to run a test with this library on a brand new angular project.  \
When I run `npm run test` the console report this error:
```
Error: node_modules/@testing-library/angular/src/lib/models.d.ts:2:28 - error TS2305: Module '"@angular/core/testing"' has no exported member 'DeferBlockState'.

2 import { ComponentFixture, DeferBlockState, TestBed } from '@angular/core/testing';
```

# Info
Environment: Debian
Angular CLI version: 16.2.1
Testing library version: 14.5.0
test runner: karma

**Comment by timdeschryver** [comment] 2023-11-17 18:25
Do you have an example that's causing this?
I thought this wouldn't be a problem, but perhaps I'm missing something...

**Comment by optimistex** [comment] 2023-11-25 19:32
@matteoveraldi I have bumped my project to the latest Angular. 

I can confirm that it works in the following combination:
____________________
  "name": "@angular/core",
  "version": "17.0.4",
____________________
  "name": "@testing-library/angular",
  "version": "14.5.0",
____________________

It seems @testing-library/angular v14.5.0 has breaking changes for Angular v15.2.10

**Comment by optimistex** [comment] 2023-11-25 19:48
On Angular 16 it still fails
_________
  "name": "@angular/core",
  "version": "16.2.12",
________
  "name": "@testing-library/angular",
  "version": "14.5.0",
_________

Failed with:
```console
Error: node_modules/@testing-library/angular/src/lib/models.d.ts:2:28 - error TS2305: Module '"@angular/core/testing"' has no exported member 'DeferBlockState'.

2 import { ComponentFixture, DeferBlockState, TestBed } from '@angular/core/testing';
                             ~~~~~~~~~~~~~~~
```

**Comment by timdeschryver** [comment] 2023-11-27 18:46
@optimistex are you importing `DeferBlockState` within your spec files?

**Comment by th3n3rd** [comment] 2023-11-28 10:07
@timdeschryver the problem is in the testing library source code: https://github.com/testing-library/angular-testing-library/blob/v14.5.0/projects/testing-library/src/lib/models.ts#L2

The [compatibility matrix](https://testing-library.com/docs/angular-testing-library/version-compatibility) shows that v14.x is ok to use for angular v16.x, but version testing library v14.5 uses several packages from [angular v17](https://github.com/testing-library/angular-testing-library/blob/v14.5.0/package.json#L34), which feels like breaking  back-compatibility, should those changes be moved to testing library v15?

**Comment by timdeschryver** [comment] 2023-11-28 11:18
Yea, @th3n3rd I'll probably do that later today.

I thought that the additional type wouldn't be a problem if it wasn't used in user's code (and this seems to be the case on a project that I'm working on ~ maybe because the usage of `skipLibCheck`).
Since it seems like it does have an impact I'll probably revert the change, and cut a v15 release.

**Comment by matteoveraldi** [comment] 2023-11-28 17:57
It works now! Thank you @timdeschryver

**Comment by optimistex** [comment] 2023-11-29 18:18
Thank you @timdeschryver !

v14.5.1 works well on Angular 16

<img width="401" alt="image" src="https://github.com/testing-library/angular-testing-library/assets/11228640/ad5898d5-71b1-4cdc-bd95-a3def937ca10">

**Comment by timdeschryver** [comment] 2023-11-29 19:15
I'm glad to hear that!
Thanks for bringing this to my attention, I'll close this issue 🎉

**Closed by timdeschryver** 2023-11-29 19:15 UTC
