### ISSUE TITLE
Investigate Angular teardown

### ISSUE THREAD

**Issue by timdeschryver** [testing-library/angular-testing-library#253] opened 2021-10-13 19:24 UTC
```
beforeAll(() => {
  TestBed.resetTestEnvironment();
  TestBed.initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting(),
    {
      teardown: {
        destroyAfterEach: true, // <-- testing module teardown
      },
    },
  );
});

beforeEach(async () => {
  await render('<p>Anything here</p>');
  // (...)
});
```

Will become the default:

https://github.com/angular/angular/pull/43353

**Comment by LayZeeDK** [comment] 2021-10-21 07:23
Thanks for your support, @timdeschryver. I'm also unable to reproduce now. It must have been a local dependency issue.

You can close this issue.

**Closed as completed** 2021-10-26 07:09 UTC
