### ISSUE TITLE
Render a component with a templateurl/styleurls

### ISSUE THREAD

**Issue by bmarshallgrowers** [testing-library/angular-testing-library#245] opened 2021-09-08 18:18 UTC
I use the Angular CLI to create my components and it generates separate css and html files for each component. When I then try to test those using this library. I get the following error 

"Unhandled Promise rejection: This test module uses the component ToolbarComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test."

could someone create an example of testing with the library when the html and css are in their own files?

**Comment by timdeschryver** [comment] 2021-09-09 08:11
Hi, this is a general question that can be caused by different factors.
The versions of angular, testing library, the test runner would be helpful.
From my experience, it should just work.

**Comment by DevFlash33** [comment] 2021-09-13 05:38
I have the same failure since the update to Angular v12 and also updated your libary, so that no peer dependency problems more appear. Im using it with jest, but i dont think that this is the failure.

**Comment by timdeschryver** [comment] 2021-09-13 09:32
Have you tried running `ngcc`? See https://github.com/testing-library/angular-testing-library/issues/66#issuecomment-593140161 for an example.

**Comment by DevFlash33** [comment] 2021-09-13 09:40
yeah this solved the issue, thank you!

**Comment by timdeschryver** [comment] 2021-09-13 09:43
Closing this issue, feel free to reopen if the issue isn't resolved.

**Closed by timdeschryver** 2021-09-13 09:43 UTC
